[package]
name = "portfolio-api"
version = "0.1.0"
edition = "2021"
authors = ["Mathieu Piton"]
description = "Backend API for Mathieu Piton's portfolio"

[dependencies]
# Web framework
actix-web = "4.9"
actix-cors = "0.7"

# Database
mongodb = "3.1"
futures = "0.3"

# Async runtime
tokio = { version = "1.43", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging and configuration
env_logger = "0.11"
log = "0.4"
dotenv = "0.15"

# Error handling
anyhow = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }
url = "2.5.4"
rss = "2.0.11"

[dev-dependencies]
# Testing
tokio-test = "0.4"
wiremock = "0.5"
