[advisories]
db-path = "~/.cargo/advisory-db"

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
]
exceptions = [
    # Use exceptions for these as they only have a single user
    { allow = ["Zlib"], crate = "tinyvec" },
    { allow = ["OpenSSL"], crate = "ring" },
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [
    # Dépendances communes qui peuvent avoir plusieurs versions
    { name = "serde" },
    { name = "serde_json" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
