[advisories]
db-path = "~/.cargo/advisory-db"
ignore = ["RUSTSEC-2024-0384"]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSD-3-Clause",
    "Unicode-3.0",
    "CC0-1.0",
    "OpenSSL",
    "Zlib",
    "MPL-2.0",
    "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 0.8
exceptions = [
    { allow = [
        "Zlib",
    ], crate = "tinyvec" },
    { allow = [
        "ISC",
        "MIT",
        "OpenSSL",
    ], crate = "ring" },
]

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
