[advisories]
db-path = "~/.cargo/advisory-db"
criteria = { vulnerability = "deny", unmaintained = "warn", yanked = "warn", notice = "warn" }

[licenses]
default = "deny"
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC", "Zlib", "MPL-2.0"]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [
    # Dépendances communes qui peuvent avoir plusieurs versions
    { name = "serde" },
    { name = "serde_json" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
