name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
  RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
  SENDER_NAME: ${{ secrets.SENDER_NAME }}
  SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  RUST_LOG: debug
  RUST_BACKTRACE: 1

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build backend
      run: |
        cd portfolio/api
        cargo build --tests --verbose

    # - name: Build frontend
    #   run: |
    #     cd portfolio/web
    #     cargo build --verbose

    - name: Run backend tests
      run: |
        cd portfolio/api
        cargo test --verbose -- --nocapture --test-threads=1

    # - name: Run frontend tests
    #   run: |
    #     cd portfolio/web
    #     cargo test --verbose -- --test-threads=1

    - name: Check formatting
      run: |
        cd portfolio/api
        cargo fmt --all -- --check

    - name: Static analysis
      run: |
        cd portfolio/api
        cargo clippy --tests -- -D warnings
